server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: Kamila2030
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled : true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.yaml